// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salasel.Infrastructure.Data;

#nullable disable

namespace Salasel.Infrastructure.Migrations
{
    [DbContext(typeof(SalaselDbContext))]
    [Migration("20260728083659_AddSupplierLocation")]
    partial class AddSupplierLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Salasel.Domain.Entities.AIProcessing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ParsedJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoiceLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoiceLogId")
                        .IsUnique();

                    b.ToTable("AIProcessings");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MasterOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("VoiceLogID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("VoiceLogID");

                    b.ToTable("MasterOrders");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantInventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<int>("CurrentQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MerchantID")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("InventoryID");

                    b.HasIndex("MerchantID");

                    b.HasIndex("ProductId");

                    b.ToTable("MerchantInventories");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantsProfile", b =>
                {
                    b.Property<int>("MerchantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MerchantID"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<decimal>("LocationLat")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("LocationLng")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MerchantID");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("MerchantsProfiles");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SubOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SubOrders");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierProducts");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProfile", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CoverageRadiusKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsActiveForRouting")
                        .HasColumnType("bit");

                    b.Property<decimal>("LocationLat")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("LocationLng")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReliabilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("SupplierID");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("SupplierProfiles");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.VoiceProcurementLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("VoiceProcurementLogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.AIProcessing", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.VoiceProcurementLog", "VoiceLog")
                        .WithOne("AIProcessing")
                        .HasForeignKey("Salasel.Domain.Entities.AIProcessing", "VoiceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoiceLog");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MasterOrder", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.MerchantsProfile", "Merchant")
                        .WithMany("MasterOrders")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salasel.Domain.Entities.VoiceProcurementLog", "VoiceLog")
                        .WithMany("MasterOrders")
                        .HasForeignKey("VoiceLogID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Merchant");

                    b.Navigation("VoiceLog");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantInventory", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.MerchantsProfile", "Merchant")
                        .WithMany("Inventories")
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salasel.Domain.Entities.Product", "Product")
                        .WithMany("MerchantInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantsProfile", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.User", "Owner")
                        .WithMany("MerchantsProfiles")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.Product", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SubOrder", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.MasterOrder", "MasterOrder")
                        .WithMany("SubOrders")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salasel.Domain.Entities.SupplierProfile", "Supplier")
                        .WithMany("SubOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProduct", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.Product", "Product")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salasel.Domain.Entities.SupplierProfile", "Supplier")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProfile", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.User", "Owner")
                        .WithMany("SupplierProfiles")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.VoiceProcurementLog", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.MerchantsProfile", "Merchant")
                        .WithMany("VoiceProcurementLogs")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MasterOrder", b =>
                {
                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantsProfile", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("MasterOrders");

                    b.Navigation("VoiceProcurementLogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.Product", b =>
                {
                    b.Navigation("MerchantInventories");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProfile", b =>
                {
                    b.Navigation("SubOrders");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.User", b =>
                {
                    b.Navigation("MerchantsProfiles");

                    b.Navigation("SupplierProfiles");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.VoiceProcurementLog", b =>
                {
                    b.Navigation("AIProcessing");

                    b.Navigation("MasterOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
