// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salasel.Infrastructure.Data;

#nullable disable

namespace Salasel.Infrastructure.Migrations
{
    [DbContext(typeof(SalaselDbContext))]
    partial class SalaselDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Salasel.Domain.Entities.FraudPreventionLimit", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<decimal>("HardLimitValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("RuleType")
                        .HasColumnType("tinyint");

                    b.HasKey("RuleID");

                    b.ToTable("FraudPreventionLimits");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantInventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MerchantID")
                        .HasColumnType("int");

                    b.Property<int>("ReorderThreshold")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryID");

                    b.HasIndex("MerchantID");

                    b.ToTable("MerchantInventories");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantsProfile", b =>
                {
                    b.Property<int>("MerchantID")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<decimal>("LocationLat")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("LocationLng")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MerchantID");

                    b.ToTable("MerchantsProfiles");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.OrderSplit", b =>
                {
                    b.Property<int>("SplitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SplitID"));

                    b.Property<byte>("FulfillmentStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("ParentOrderID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotalCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("SplitID");

                    b.HasIndex("ParentOrderID");

                    b.HasIndex("SupplierID");

                    b.ToTable("OrderSplits");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.OrderTransaction", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<byte>("ApprovalStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MerchantID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalOrderCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("VoiceLogID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("MerchantID");

                    b.HasIndex("VoiceLogID");

                    b.ToTable("OrderTransactions");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierCatalog", b =>
                {
                    b.Property<int>("CatalogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogID"));

                    b.Property<int>("DeliveryLeadTime_Days")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockAvailable")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VectorEmbedding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatalogID");

                    b.HasIndex("SupplierID");

                    b.ToTable("SupplierCatalogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProfile", b =>
                {
                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActiveForRouting")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReliabilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("SupplierID");

                    b.ToTable("SupplierProfiles");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("ActionPerformed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminUserID")
                        .HasColumnType("int");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditID");

                    b.HasIndex("AdminUserID");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.VoiceProcurementLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("LLMParsedJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MerchantID")
                        .HasColumnType("int");

                    b.Property<decimal>("NLPConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawAudioURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranscribedAmiyaText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.HasIndex("MerchantID");

                    b.ToTable("VoiceProcurementLogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantInventory", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.MerchantsProfile", "Merchant")
                        .WithMany("Inventories")
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantsProfile", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.User", "User")
                        .WithOne("MerchantsProfile")
                        .HasForeignKey("Salasel.Domain.Entities.MerchantsProfile", "MerchantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.OrderSplit", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.OrderTransaction", "ParentOrder")
                        .WithMany("OrderSplits")
                        .HasForeignKey("ParentOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salasel.Domain.Entities.SupplierProfile", "Supplier")
                        .WithMany("OrderSplits")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.OrderTransaction", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.MerchantsProfile", "Merchant")
                        .WithMany("OrderTransactions")
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salasel.Domain.Entities.VoiceProcurementLog", "VoiceLog")
                        .WithMany("OrderTransactions")
                        .HasForeignKey("VoiceLogID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Merchant");

                    b.Navigation("VoiceLog");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierCatalog", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.SupplierProfile", "Supplier")
                        .WithMany("SupplierCatalogs")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProfile", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.User", "User")
                        .WithOne("SupplierProfile")
                        .HasForeignKey("Salasel.Domain.Entities.SupplierProfile", "SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SystemAuditLog", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.User", "AdminUser")
                        .WithMany("SystemAuditLogs")
                        .HasForeignKey("AdminUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.VoiceProcurementLog", b =>
                {
                    b.HasOne("Salasel.Domain.Entities.MerchantsProfile", "Merchant")
                        .WithMany("VoiceProcurementLogs")
                        .HasForeignKey("MerchantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.MerchantsProfile", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderTransactions");

                    b.Navigation("VoiceProcurementLogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.OrderTransaction", b =>
                {
                    b.Navigation("OrderSplits");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.SupplierProfile", b =>
                {
                    b.Navigation("OrderSplits");

                    b.Navigation("SupplierCatalogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.User", b =>
                {
                    b.Navigation("MerchantsProfile");

                    b.Navigation("SupplierProfile");

                    b.Navigation("SystemAuditLogs");
                });

            modelBuilder.Entity("Salasel.Domain.Entities.VoiceProcurementLog", b =>
                {
                    b.Navigation("OrderTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
