// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB68nzfPLAwZmk43Silxxihu3g7dWfmZzc',
    appId: '1:492818497742:web:c3c6a761c45d3e4406509f',
    messagingSenderId: '492818497742',
    projectId: 'salasel-308fa',
    authDomain: 'salasel-308fa.firebaseapp.com',
    storageBucket: 'salasel-308fa.firebasestorage.app',
    measurementId: 'G-4GZB2Q0CQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaGGd1jE-xh-P9CRQ6378eX5DIg24c2qs',
    appId: '1:492818497742:android:bf4e7ebef39aaea206509f',
    messagingSenderId: '492818497742',
    projectId: 'salasel-308fa',
    storageBucket: 'salasel-308fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOGPo0pcMaxcRifEsqciPpLSfoeibbnJ0',
    appId: '1:492818497742:ios:52a3d7637ca83f3606509f',
    messagingSenderId: '492818497742',
    projectId: 'salasel-308fa',
    storageBucket: 'salasel-308fa.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOGPo0pcMaxcRifEsqciPpLSfoeibbnJ0',
    appId: '1:492818497742:ios:52a3d7637ca83f3606509f',
    messagingSenderId: '492818497742',
    projectId: 'salasel-308fa',
    storageBucket: 'salasel-308fa.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB68nzfPLAwZmk43Silxxihu3g7dWfmZzc',
    appId: '1:492818497742:web:30a26d17444e0f4506509f',
    messagingSenderId: '492818497742',
    projectId: 'salasel-308fa',
    authDomain: 'salasel-308fa.firebaseapp.com',
    storageBucket: 'salasel-308fa.firebasestorage.app',
    measurementId: 'G-4Y346DSVB9',
  );
}
