name: .NET Core CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore backend-dotnet/Salasel.sln

    - name: Build Solution
      run: dotnet build backend-dotnet/Salasel.sln --no-restore --configuration Release

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: actions/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: actions/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./backend-dotnet
        file: ./backend-dotnet/Dockerfile
        push: true
        tags: |
          abdelrahmansaeed369/salasel-api:latest
          abdelrahmansaeed369/salasel-api:${{ github.sha }}
